### ISSUE TITLE
SQL file

### ISSUE THREAD

**Issue by wapnishantha** [Stevec4/Joomla-HelloWorld#1]
https://github.com/Stevec4/Joomla-HelloWorld/blob/164a094bba3215c8d18a78ea59da42c516755f19/17%20Adding%20a%20front-end%20form/helloworld.xml#L22

Can you please add SQL file?

**Comment by Stevec4** [comment]
I am showing the file is in the sql folder, already are you having a specific issue?

```
DROP TABLE IF EXISTS `#__helloworld`;

CREATE TABLE `#__helloworld` (
	`id`       INT(11)     NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10)     NOT NULL DEFAULT '0',
	`created`  DATETIME    NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created_by`  INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`greeting` VARCHAR(25) NOT NULL,
	`published` tinyint(4) NOT NULL,
	`catid`	    int(11)    NOT NULL DEFAULT '0',
	`params`   VARCHAR(1024) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`)
)
	ENGINE =MyISAM
	AUTO_INCREMENT =0
	DEFAULT CHARSET =utf8;

INSERT INTO `#__helloworld` (`greeting`) VALUES
('Hello World!'),
('Good Bye World!');
```

**Comment by Stevec4** [comment]
this is to alter the tables and is file 0.0.16.sql
```
ALTER TABLE`#__helloworld` ADD COLUMN `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER `asset_id`;
ALTER TABLE`#__helloworld` ADD COLUMN `created_by` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `created`;
```

**Comment by Stevec4** [comment]
git will not upload empty files so the empty update files are not displayed, but are in the zip archive.
Steve

**Comment by wapnishantha** [comment]
I just download ZIP from https://github.com/Stevec4/Joomla-HelloWorld/tree/master/17%20Adding%20a%20front-end%20form 

seems there isn't sql folder with sql fills

**Comment by wapnishantha** [comment]
Error as follows 
![image](https://user-images.githubusercontent.com/4719674/38171426-2e35e1ac-35b7-11e8-852d-1cc056e43c3c.png)

**Comment by Stevec4** [comment]
Thats odd I just downloaded the same zip and the files are there. What version of Joomla are you using?

**Comment by wapnishantha** [comment]
Joomla  3.8

Opz  did you get sql folder form this https://github.com/Stevec4/Joomla-HelloWorld/blob/master/17%20Adding%20a%20front-end%20form/helloworld.zip ?

**Comment by wapnishantha** [comment]
Just now I saw SQL folder, it's under  admin folder 
![image](https://user-images.githubusercontent.com/4719674/38171913-728e3ce2-35c0-11e8-99b3-b34c2ca39f5c.png)

**Comment by wapnishantha** [comment]
May be it;s problem of Joomla version, What is the version that you used?

**Comment by Stevec4** [comment]
I have installed it on 3.8.5
The path is correct admin/sql/install.mysql.utf8.sql
I did see something on the joomla forum about a MySQL error let me do some
digging

**Comment by wapnishantha** [comment]
ok thanks @Stevec4

**Comment by Stevec4** [comment]
@wapnishantha are you using php 7.2 by chance? When I try installing it using php 7.2, I receive the same error but on php 7.1 it installs fine.
Steve

**Comment by Stevec4** [comment]
@wapnishantha thank you for pointing out the mistake. I think the repository is now fully updated and correct. It will take a day or so for me to get the zipfiles re uploaded but everything else should be ok.
Steve

**Comment by wapnishantha** [comment]
Server configuration as followers. By the way thanks for your prompt reply and all. I will go through the your code and hope to build new component. I will let you know once it finished 👍  

![image](https://user-images.githubusercontent.com/4719674/38180918-87090dfe-364d-11e8-9294-fd9b6bdec5b0.png)

**Comment by Stevec4** [comment]
good luck, you should watch Robbie's videos associated with the tutorial you will gain a much better understanding of the api's.
Steve

**Comment by wapnishantha** [comment]
:+1:
